// MagicLinkSignIn email template — "Sign in to your customer portal" (E-01).
//
// Sent by sendPortalSignInLink with a sign-in link generated by the Firebase
// Admin SDK. Branded with the business whose portal the customer came from (a
// verified custom domain); on the shared portal host it carries the platform
// name, because a customer there may deal with several businesses. The header
// shows the name, not a logo: tenant settings don't hold an email-safe
// immutable logo copy (A-06 keeps those on documents only).

import { Section, Text } from "@react-email/components";
import {
  TenantEmailLayout,
  type TenantSnapshotForEmail,
} from "../components/TenantEmailLayout";
import { Button } from "../components/Button";
import { sanitizeEmailField } from "../sanitize";

export interface MagicLinkSignInProps {
  tenant: TenantSnapshotForEmail;
  signInUrl: string;
}

export function buildMagicLinkSignInPreviewText(
  props: Pick<MagicLinkSignInProps, "tenant">,
): string {
  const tenant = sanitizeEmailField(props.tenant.name, 80) || "your customer portal";
  return `Your sign-in link for ${tenant} — view and pay your invoices and quotes`.slice(
    0,
    110,
  );
}

export function MagicLinkSignIn(props: MagicLinkSignInProps) {
  const safeTenantName =
    sanitizeEmailField(props.tenant.name, 100) || "your provider";
  const preview = buildMagicLinkSignInPreviewText(props);

  return (
    <TenantEmailLayout tenant={props.tenant} preview={preview}>
      <Section>
        <Text
          style={{
            fontSize: "18px",
            fontWeight: 600,
            margin: "0 0 12px 0",
            color: "#111111",
          }}
        >
          Sign in to your customer portal
        </Text>
        <Text
          style={{
            fontSize: "14px",
            lineHeight: "22px",
            margin: "0 0 16px 0",
            color: "#374151",
          }}
        >
          Use the button below to sign in and see your invoices and quotes from{" "}
          {safeTenantName}.
        </Text>
      </Section>

      <Section style={{ textAlign: "center", margin: "24px 0" }}>
        <Button href={props.signInUrl} primaryColor={props.tenant.primaryColor}>
          Sign in
        </Button>
      </Section>

      <Section>
        <Text
          style={{
            fontSize: "12px",
            lineHeight: "18px",
            color: "#6b7280",
            margin: "0 0 8px 0",
          }}
        >
          If the button doesn&apos;t work, copy this link into your browser:
        </Text>
        <Text
          style={{
            fontSize: "12px",
            lineHeight: "18px",
            color: "#6b7280",
            margin: "0 0 16px 0",
            wordBreak: "break-all",
          }}
        >
          {props.signInUrl}
        </Text>
        <Text
          style={{
            fontSize: "12px",
            lineHeight: "18px",
            color: "#6b7280",
            margin: "0",
          }}
        >
          If you didn&apos;t ask to sign in, you can safely ignore this email.
        </Text>
      </Section>
    </TenantEmailLayout>
  );
}
